### ISSUE TITLE
/altair endpoint not found

### ISSUE THREAD

**Issue by moufmouf** [XKojiMedia/laravel-altair-graphql#1]
Hey!

I just gave a shot to this library and I'm having trouble with accessing Altair.
I'm not sure what is wrong. I'm using Laravel 5.7 (with GraphQLite) and I just installed the package using:

```
composer require xkojimedia/laravel-altair-graphql
```

But when I try to access "/altair", I get a 404 error.

Also, when I run:

```
php artisan vendor:publish --provider="XKojiMedia\AltairGraphQL\AltairGraphQLServiceProvider" --tag=config
```

no configuration is published in the /config folder.

**Comment by imolorhe** [comment]
Did you provide it in your laravel app?

```
'providers' => [
    // Other providers...
    XKojiMedia\AltairGraphQL\AltairGraphQLServiceProvider::class,
]
```

**Comment by moufmouf** [comment]
Indeed, the provider was not part of my configuration.
The funny thing is that my Laravel version is 5.7 so I would have expected Laravel's service provider autodiscovery to do this for me.

**Comment by moufmouf** [comment]
Sorry for the issue. Strangely, it seems to work now. I'm closing this.
